services:
  groupme-backup:
    build: .
    environment:
      DATABASE: '/database.db'  # Full path to sqlite database file to use as a backup destination
      GROUP_ID: 12345  # ID of the group to back up
      TOKEN: # Your GroupMe API token
    image: ghcr.io/williamjacksn/groupme-backup
    init: true

  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/williamjacksn/groupme-backup
    init: true
    volumes:
      - ./:/app
