version: '3'

services:
  groupme-backup:
    image: docker.pkg.github.com/williamjacksn/groupme-backup/groupme-backup
    build: .
    environment:
      DATABASE: '/database.db'  # Full path to sqlite database file to use as a backup destination
      GROUP_ID: 12345  # ID of the group to back up
      TOKEN: # Your GroupMe API token
